from db_models.factories import (
    CategoryFactory,
    CategoryTypeFactory,
    ChildCategoryFactory,
    ImageFactory,
    AuthorFactory,
    ProductTypeFactory,
    AddressFactory,
    LocationFactory,
    ShopSettingFactory,
    ShopFactory,
    ShippingFactory,
    ProductFactory,
    RatingFactory,
)

FACTORIES = (
    CategoryFactory,
    CategoryTypeFactory,
    ChildCategoryFactory,
    ImageFactory,
    AuthorFactory,
    ProductTypeFactory,
    AddressFactory,
    LocationFactory,
    ShopSettingFactory,
    ShopFactory,
    ShippingFactory,
    ProductFactory,
    RatingFactory,
)
